php artisan make:model about
php artisan make:model cart
php artisan make:model cartdetail
php artisan make:model category
php artisan make:model categorynew
php artisan make:model contact
php artisan make:model content
php artisan make:model contenttag
php artisan make:model customer
php artisan make:model failed_jobs
php artisan make:model feeback
php artisan make:model footer
php artisan make:model hotro
php artisan make:model importbill
php artisan make:model importbilldetail
php artisan make:model menu
php artisan make:model menutype
php artisan make:model migrations
php artisan make:model model_has_permissions
php artisan make:model model_has_roles
php artisan make:model news
php artisan make:model order
php artisan make:model orderdetail
php artisan make:model password_resets
php artisan make:model password_reset_tokens
php artisan make:model payment
php artisan make:model permissions
php artisan make:model personal_access_tokens
php artisan make:model price
php artisan make:model product
php artisan make:model producttag
php artisan make:model promotion
php artisan make:model provider
php artisan make:model roles
php artisan make:model role_has_permissions
php artisan make:model room
php artisan make:model roomdetail
php artisan make:model silde
php artisan make:model stuff
php artisan make:model sysdiagrams
php artisan make:model tag
php artisan make:model user
php artisan make:model usergroup
php artisan make:model users
php artisan make:model wishlist
php artisan make:model wishlistdetail
