php artisan make:controller about --resource
php artisan make:controller cart --resource
php artisan make:controller cartdetail --resource
php artisan make:controller category --resource
php artisan make:controller categorynew --resource
php artisan make:controller contact --resource
php artisan make:controller content --resource
php artisan make:controller contenttag --resource
php artisan make:controller customer --resource
php artisan make:controller failed_jobs --resource
php artisan make:controller feeback --resource
php artisan make:controller footer --resource
php artisan make:controller hotro --resource
php artisan make:controller importbill --resource
php artisan make:controller importbilldetail --resource
php artisan make:controller menu --resource
php artisan make:controller menutype --resource
php artisan make:controller migrations --resource
php artisan make:controller model_has_permissions --resource
php artisan make:controller model_has_roles --resource
php artisan make:controller news --resource
php artisan make:controller order --resource
php artisan make:controller orderdetail --resource
php artisan make:controller password_resets --resource
php artisan make:controller password_reset_tokens --resource
php artisan make:controller payment --resource
php artisan make:controller permissions --resource
php artisan make:controller personal_access_tokens --resource
php artisan make:controller price --resource
php artisan make:controller product --resource
php artisan make:controller producttag --resource
php artisan make:controller promotion --resource
php artisan make:controller provider --resource
php artisan make:controller roles --resource
php artisan make:controller role_has_permissions --resource
php artisan make:controller room --resource
php artisan make:controller roomdetail --resource
php artisan make:controller silde --resource
php artisan make:controller stuff --resource
php artisan make:controller sysdiagrams --resource
php artisan make:controller tag --resource
php artisan make:controller user --resource
php artisan make:controller usergroup --resource
php artisan make:controller users --resource
php artisan make:controller wishlist --resource
php artisan make:controller wishlistdetail --resource
